Repository symfony/maker-bundle, pull requests merged in 2020-11, with the labels that each got.

#719 Fix: Caching of composer deps
  .github/workflows/ci.yml
Labels: Status: Reviewed

#735 stop php-cs-fixer from complaining in CI
  src/Util/ClassSourceManipulator.php
Labels: Related Tests Pass, Status: Needs Review

#728 improve php8 attribute support in makers
  composer.json
  src/Generator.php
  src/Maker/AbstractMaker.php
  src/Maker/MakeController.php
  src/Maker/MakeCrud.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Resources/config/services.xml
  src/Util/PhpCompatUtil.php
  tests/Command/MakerCommandTest.php
  tests/Doctrine/EntityRegeneratorTest.php
  tests/GeneratorTest.php
  tests/Util/PhpVersionTest.php
Labels: Related Tests Pass, Status: Needs Review

#742 update test details for new flex recipes
  src/Test/MakerTestDetails.php
Labels: Related Tests Pass, Status: Needs Review

#743 Rename ci.yml to ci.yaml
  .github/workflows/ci.yaml
Labels: Status: Reviewed

#746 Allow released versions of the deprecation contract
  composer.json
Labels: Status: Reviewed

#749 fixed typo in postgres extension name
  src/Docker/DockerDatabaseServices.php
Labels: Related Tests Pass, Status: Reviewed
