Repository symfony/maker-bundle, pull requests merged in 2021-05, with the labels that each got.

#867 [ci] upgrade php-cs-fixer 2.x -> 3.0
  .gitignore
  .php-cs-fixer.dist.php
  composer.json
  src/Resources/test/.php_cs.test
Labels: Status: Needs Work

#871 [make:registration] URL should be escaped
  src/Resources/skeleton/registration/twig_email.tpl.php
Labels: Status: Reviewed

#873 Update code example
  src/Resources/doc/index.rst
Labels: Related Tests Pass, Status: Reviewed

#874 [ci] set server version in dsn
  .github/workflows/ci.yaml
  phpunit.xml.dist
  src/Test/MakerTestDetails.php
Labels: Related Tests Pass, Status: Needs Review

#877 [make:entity] Default to "datetime_immutable" when creating entities
  src/Maker/MakeEntity.php
Labels: Status: Reviewed

#884 [changelog] add missing changelog entry for 1.31.1
  CHANGELOG.md
Labels: Status: Needs Review
