Repository symfony/maker-bundle, pull requests merged in 2021-01, with the labels that each got.

#776 [make:registration] allow email verification without authentication
  src/Maker/MakeRegistrationForm.php
  src/Resources/config/makers.xml
  src/Resources/skeleton/registration/RegistrationController.tpl.php
  src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
  tests/Maker/MakeRegistrationFormTest.php
  tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/config/packages/mailer.yaml
  tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/config/packages/security.yaml
  tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/src/Controller/MyController.php
  tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/src/Entity/User.php
  tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/src/Repository/UserRepository.php
  tests/fixtures/MakeRegistrationFormVerifyEmailNoAuthFunctionalTest/tests/VerifyEmailTest.php
Labels: Related Tests Pass, Status: Needs Review

#781 Use assertStringNotContainsString instead of assertNotContains
  tests/Maker/MakeEntityTest.php
  tests/Maker/MakeMigrationTest.php
Labels: Related Tests Pass, Status: Reviewed

#778 Move symfony/process dependency from require-dev to require
  src/Test/MakerTestCase.php
Labels: Related Tests Pass, Status: Reviewed

#780 Fixed PHP 7.1.3 tests by using PHPUnit 8.5
  src/Test/MakerTestEnvironment.php
Labels: Related Tests Pass, Status: Reviewed

#740 Update MakerFileLinkFormatter.php
  src/Util/MakerFileLinkFormatter.php
Labels: Status: Needs Work

#785 [Reset-Password] use expiration translation in check email route
  src/Maker/MakeResetPassword.php
  src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
  src/Resources/skeleton/resetPassword/twig_check_email.tpl.php
Labels: Status: Needs Review

#791 [CI] fix php-cs-fixer squawks in CI
  src/Console/MigrationDiffFilteredOutput.php
  src/FileManager.php
  src/Maker/MakeEntity.php
  src/Maker/MakeUser.php
  src/Test/MakerTestEnvironment.php
  src/Util/PhpCompatUtil.php
  src/Util/YamlSourceManipulator.php
  src/Validator.php
  tests/Util/PhpVersionTest.php
Labels: Status: Needs Review

#792 Make commands compatible with LazyCommand
  src/DependencyInjection/CompilerPass/MakeCommandRegistrationPass.php
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeCommand.php
  src/Maker/MakeController.php
  src/Maker/MakeCrud.php
  src/Maker/MakeDockerDatabase.php
  src/Maker/MakeEntity.php
  src/Maker/MakeFixtures.php
  src/Maker/MakeForm.php
  src/Maker/MakeFunctionalTest.php
  src/Maker/MakeMessage.php
  src/Maker/MakeMessengerMiddleware.php
  src/Maker/MakeMigration.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Maker/MakeSerializerEncoder.php
  src/Maker/MakeSerializerNormalizer.php
  src/Maker/MakeSubscriber.php
  src/Maker/MakeTwigExtension.php
  src/Maker/MakeUnitTest.php
  src/Maker/MakeUser.php
  src/Maker/MakeValidator.php
  src/Maker/MakeVoter.php
  src/MakerInterface.php
  src/Resources/skeleton/command/Command.tpl.php
Labels: Status: Reviewed

#795 Support running make:migration non-interactively
  src/Maker/MakeMigration.php
  src/MakerInterface.php
  tests/Maker/FunctionalTest.php
  tests/fixtures/MakeCommandInCustomRootNamespace/tests/GeneratedCommandTest.php
Labels: Related Tests Pass, Status: Reviewed
