Repository symfony/maker-bundle, pull requests merged in 2021-06, with the labels that each got.

#890 [make:user] Keep implementing deprecated username methods
  src/Resources/skeleton/security/UserProvider.tpl.php
  src/Security/UserClassBuilder.php
  tests/Security/fixtures/expected/UserEntityWithEmailAsIdentifier.php
  tests/Security/fixtures/expected/UserEntityWithPassword.php
  tests/Security/fixtures/expected/UserEntityWithUser_IdentifierAsIdentifier.php
  tests/Security/fixtures/expected/UserEntityWithoutPassword.php
  tests/Security/fixtures/expected/UserModelWithEmailAsIdentifier.php
  tests/Security/fixtures/expected/UserModelWithPassword.php
  tests/Security/fixtures/expected/UserModelWithoutPassword.php
Labels: Status: Reviewed

#899 Use proper name for parameter of upgradePassword
  src/Resources/skeleton/doctrine/Repository.tpl.php
Labels: Related Tests Pass, Status: Reviewed

#889 [make:user] Use password_hashers instead of encoders
  src/Maker/MakeUser.php
  src/Resources/skeleton/security/UserProvider.tpl.php
  src/Security/SecurityConfigUpdater.php
  tests/Security/SecurityConfigUpdaterTest.php
  tests/Security/yaml_fixtures/expected_authenticator/empty_source.yaml
  tests/Security/yaml_fixtures/expected_authenticator/security_52_empty_source.yaml
  tests/Security/yaml_fixtures/expected_authenticator/security_52_with_multiple_authenticators.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/empty_source_model_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/entity_username_no_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/model_email_password_existing_providers.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/model_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/model_username_no_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/security_52_complex_entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/security_52_entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/simple_security_with_single_memory_provider_configured.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/empty_source_model_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/entity_username_no_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/model_email_password_existing_providers.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/model_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/model_username_no_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/security_52_complex_entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/security_52_entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/simple_security_with_single_memory_provider_configured.yaml
  tests/Security/yaml_fixtures/source/empty_security.yaml
  tests/Security/yaml_fixtures/source/security_52_with_multiple_authenticators.yaml
Labels: Related Tests Pass

#913 [make:registration] conditionally generate verify email flash in template
  src/Maker/MakeRegistrationForm.php
  src/Resources/skeleton/registration/twig_template.tpl.php
Labels: Related Tests Pass, Status: Needs Review

#895 [make:crud] send the proper HTTP status codes and use renderForm() when available
  src/Maker/MakeCrud.php
  src/Resources/skeleton/crud/controller/Controller.tpl.php
Labels: Related Tests Pass
