Repository symfony/maker-bundle, pull requests merged in 2022-05, with the labels that each got.

#1106 [make:*] use sorted use statements
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeCommand.php
  src/Maker/MakeController.php
  src/Maker/MakeCrud.php
  src/Maker/MakeForm.php
  src/Maker/MakeFunctionalTest.php
  src/Maker/MakeMessage.php
  src/Maker/MakeMessengerMiddleware.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Maker/MakeSerializerEncoder.php
  src/Maker/MakeSerializerNormalizer.php
  src/Maker/MakeSubscriber.php
  src/Maker/MakeTest.php
  src/Maker/MakeTwigExtension.php
  src/Maker/MakeUnitTest.php
  src/Renderer/FormTypeRenderer.php
  src/Resources/config/makers.xml
  src/Resources/skeleton/command/Command.tpl.php
  src/Resources/skeleton/controller/Controller.tpl.php
  src/Resources/skeleton/crud/controller/Controller.tpl.php
  src/Resources/skeleton/event/Subscriber.tpl.php
  src/Resources/skeleton/form/Type.tpl.php
  src/Resources/skeleton/message/MessageHandler.tpl.php
  src/Resources/skeleton/middleware/Middleware.tpl.php
  src/Resources/skeleton/resetPassword/ChangePasswordFormType.tpl.php
  src/Resources/skeleton/resetPassword/ResetPasswordRequestFormType.tpl.php
  src/Resources/skeleton/serializer/Encoder.tpl.php
  src/Resources/skeleton/serializer/Normalizer.tpl.php
  src/Resources/skeleton/test/Functional.tpl.php
  src/Resources/skeleton/test/Unit.tpl.php
  src/Resources/skeleton/twig/Extension.tpl.php
  src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
  src/Util/TemplateComponentGenerator.php
  src/Util/UseStatementGenerator.php
  tests/Maker/MakeCommandTest.php
  tests/Util/TemplateComponentGeneratorTest.php
  tests/Util/UseStatementGeneratorTest.php
Labels: Status: Needs Review, Minor

#1107 [make:user] Legacy <= 5.3 & Doctrine Cleanup
  composer.json
  src/DependencyInjection/CompilerPass/SetDoctrineManagerRegistryClassPass.php
  src/Doctrine/EntityClassGenerator.php
  src/Maker/MakeEntity.php
  src/Maker/MakeUser.php
  src/MakerBundle.php
  src/Resources/config/makers.xml
  src/Resources/skeleton/doctrine/Entity.tpl.php
  src/Resources/skeleton/doctrine/Repository.tpl.php
  src/Resources/skeleton/security/UserProvider.tpl.php
  src/Security/SecurityConfigUpdater.php
  src/Security/UserClassBuilder.php
  tests/Doctrine/EntityRegeneratorTest.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php
  tests/Maker/MakeUserTest.php
  tests/Security/UserClassBuilderTest.php
  tests/Security/fixtures/expected/legacy_5_user_class/UserEntityWithoutPassword.php
  tests/Security/fixtures/expected/legacy_5_user_class/UserModelWithoutPassword.php
  tests/Security/fixtures/expected/legacy_get_password/UserEntityNoPassword.php
  tests/Security/fixtures/expected/legacy_get_password/UserEntityWithPassword.php
  tests/Security/fixtures/expected/legacy_get_password/UserModelNoPassword.php
  tests/Security/fixtures/expected/legacy_get_password/UserModelWithPassword.php
  tests/Security/fixtures/expected/legacy_get_username/UserEntityGetUsername.php
  tests/Security/fixtures/expected/legacy_get_username/UserModelGetUsername.php
  tests/Security/fixtures/expected/legacy_get_username/UserModelWithEmailAsUsername.php
  tests/fixtures/make-auth/LoginFlowTest.php.twig
Labels: Feature, Status: Needs Review

#1111 cleanup legacy code in tests
  src/Util/PhpCompatUtil.php
  tests/Maker/MakeAuthenticatorTest.php
  tests/Maker/MakeCrudTest.php
  tests/Maker/MakeEntityTest.php
  tests/Maker/MakeMigrationTest.php
  tests/Maker/MakeRegistrationFormTest.php
  tests/Maker/MakeResetPasswordTest.php
  tests/Maker/MakeTestTest.php
  tests/fixtures/make-registration-form/standard_setup/src/Security/LegacyGuardStubAuthenticator.php
Labels: Status: Needs Review, Minor

#1109 Add missing types in code templates
  src/Maker/MakeVoter.php
  src/Resources/skeleton/doctrine/Repository.tpl.php
  src/Resources/skeleton/event/Subscriber.tpl.php
  src/Resources/skeleton/message/Message.tpl.php
  src/Resources/skeleton/security/UserProvider.tpl.php
  src/Resources/skeleton/security/Voter.tpl.php
  src/Resources/skeleton/serializer/Encoder.tpl.php
  src/Resources/skeleton/serializer/Normalizer.tpl.php
  src/Resources/skeleton/validator/Constraint.tpl.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php
Labels: Feature, Status: Reviewed

#1108 [make:test] Removal of the condition requiring a php version < 8.1
  src/Maker/MakeTest.php
Labels: Bug, Status: Reviewed

#1028 Add typed properties for make:reset-password and make:registration
  src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
  src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
Labels: Feature, Status: Reviewed

#858 [make:controller] avoid require doctrine/annotation when can use attributes
  src/Maker/MakeController.php
  src/Resources/config/makers.xml
  tests/Maker/MakeControllerTest.php
Labels: Feature, Status: Reviewed

#1075 [make:stimulus-controller] New Stimulus controller Maker command
  src/Maker/MakeStimulusController.php
  src/Resources/config/makers.xml
  src/Resources/help/MakeStimulusController.txt
  src/Resources/skeleton/stimulus/Controller.tpl.php
  tests/Maker/MakeStimulusControllerTest.php
  tests/fixtures/make-stimulus-controller/with_targets.js
  tests/fixtures/make-stimulus-controller/without_targets.js
Labels: Feature, Status: Reviewed

#1054 make:entity Use the namespace instead of the full class name for MappingDriver
  src/Doctrine/DoctrineHelper.php
Labels: Bug, Status: Reviewed

#1112 [git-released] v1.41.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#456 Use prefix "is" for getters on boolean fields
  src/Util/ClassSourceManipulator.php
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/fixtures/add_getter/User_simple_bool.php
Labels: Feature, Status: Reviewed

#307 [make:crud][experimental] Add generated tests to make:crud
  src/Maker/MakeCrud.php
  src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
  src/Resources/skeleton/crud/test/Test.tpl.php
  tests/Maker/MakeCrudTest.php
Labels: Feature, Status: Needs Review

#1116 [git-released] v1.42.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1120 [make:controller] Return a JsonResponse instead of a Response with --no-template
  src/Maker/MakeController.php
  src/Resources/skeleton/controller/Controller.tpl.php
  tests/fixtures/make-controller/tests/it_generates_a_controller.php
Labels: Feature, Status: Reviewed

#1118 Fix errors when enable_authenticator_manager is not set
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeRegistrationForm.php
Labels: Bug, Status: Needs Work, Status: Reviewed

#1042 [CSM] fix: Handle enum as values
  src/Util/ClassSourceManipulator.php
Labels: Bug, Status: Reviewed

#1121 [git-released] v1.43.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1122 drop PHP 7.x support
  .github/workflows/ci.yaml
  appveyor.yml
  composer.json
  src/Command/MakerCommand.php
  src/Doctrine/DoctrineHelper.php
  src/Generator.php
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeCommand.php
  src/Maker/MakeController.php
  src/Maker/MakeCrud.php
  src/Maker/MakeEntity.php
  src/Maker/MakeForm.php
  src/Maker/MakeMessage.php
  src/Maker/MakeMigration.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Maker/MakeSubscriber.php
  src/Maker/MakeUser.php
  src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php
  src/Resources/skeleton/command/Command.tpl.php
  src/Resources/skeleton/crud/controller/Controller.tpl.php
  src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
  src/Resources/skeleton/crud/test/Test.tpl.php
  src/Resources/skeleton/doctrine/Entity.tpl.php
  src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
  src/Resources/skeleton/serializer/Normalizer.tpl.php
  src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
  src/Security/SecurityControllerBuilder.php
  src/Util/PhpCompatUtil.php
  src/Util/TemplateComponentGenerator.php
  tests/Maker/MakeCommandTest.php
  tests/Maker/MakeCrudTest.php
  tests/Maker/MakeEntityTest.php
  tests/Maker/MakeResetPasswordTest.php
  tests/Security/SecurityControllerBuilderTest.php
  tests/Security/fixtures/expected/legacy_add_login_logout_method/SecurityController_login_logout.php
  tests/Security/fixtures/expected/legacy_add_login_method/SecurityController_login.php
  tests/Security/fixtures/expected/legacy_add_logout_method/SecurityController_logout.php
  tests/Util/PhpVersionTest.php
  tests/Util/TemplateComponentGeneratorTest.php
  tests/fixtures/make-crud/legacy/SweetFood-custom-namespace.php
  tests/fixtures/make-crud/legacy/SweetFood.php
  tests/fixtures/make-crud/legacy/SweetFoodCustomRepository.php
  tests/fixtures/make-crud/legacy/SweetFoodRepository.php
  tests/fixtures/make-crud/legacy/expected/WithCustomRepository.php
  tests/fixtures/make-entity/entities/annotations/User-basic.php
  tests/fixtures/make-entity/entities/annotations/User-custom-namespace.php
  tests/fixtures/make-entity/entities/annotations/User-invalid-method-no-property.php
  tests/fixtures/make-entity/entities/annotations/User-invalid-method.php
  tests/fixtures/make-entity/entities/annotations/UserAvatarPhoto-basic.php
  tests/fixtures/make-entity/regenerate-embeddable/annotations/src/Entity/Food.php
  tests/fixtures/make-entity/regenerate-embeddable/annotations/src/Entity/Recipe.php
  tests/fixtures/make-entity/regenerate-embedded/annotations/src/Entity/Currency.php
  tests/fixtures/make-entity/regenerate-embedded/annotations/src/Entity/Invoice.php
  tests/fixtures/make-entity/regenerate-embedded/annotations/src/Entity/Money.php
  tests/fixtures/make-entity/regenerate/annotations/src/Entity/User.php
  tests/fixtures/make-entity/regenerate/annotations/src/Entity/UserAvatar.php
Labels: Feature, Status: Reviewed

#1123 [make:reset-password] cleanup legacy code
  src/Maker/MakeResetPassword.php
  src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
  tests/Maker/MakeResetPasswordTest.php
Labels: Minor

#1127 update php-cs-fixer ruleset for php8
  .php-cs-fixer.dist.php
  src/Doctrine/EntityDetails.php
  src/Doctrine/EntityRegenerator.php
  src/Doctrine/EntityRelation.php
  src/FileManager.php
  src/GeneratorTwigHelper.php
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeEntity.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Maker/MakeUser.php
  src/Renderer/FormTypeRenderer.php
  src/Security/SecurityConfigUpdater.php
  src/Security/SecurityControllerBuilder.php
  src/Test/MakerTestCase.php
  src/Util/AutoloaderUtil.php
  src/Util/ClassDetails.php
  src/Util/ClassNameDetails.php
  src/Util/ClassNameValue.php
  src/Util/UseStatementGenerator.php
  src/Util/YamlSourceManipulator.php
  tests/DependencyBuilderTest.php
  tests/Maker/MakeMessageTest.php
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/ComposeFileManipulatorTest.php
  tests/Util/UseStatementGeneratorTest.php
  tests/Util/YamlSourceManipulatorTest.php
Labels: Status: Needs Review, Minor

#1129 [tests] bring test suite up to PHP8 standards
  src/Test/MakerTestCase.php
  src/Test/MakerTestDetails.php
  src/Test/MakerTestEnvironment.php
  src/Test/MakerTestKernel.php
  src/Test/MakerTestProcess.php
  src/Test/MakerTestRunner.php
Labels: Feature, Status: Needs Review

#1133 [ci] add symfony 6.2 to ci
  .github/workflows/ci.yaml
Labels: Status: Needs Review, Minor

#1132 [csm] fix incomplete test
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/fixtures/source/ProductWithTabs.php
  tests/Util/fixtures/with_tabs/ProductWithTabs.php
Labels: Status: Needs Work, Minor
