Repository symfony/maker-bundle, pull requests merged in 2022-07, with the labels that each got.

#1143 [Generator] correct createClassNameDetails doc
  src/Generator.php
Labels: Minor

#1139 [make:entity] Improve uid support
  src/Maker/MakeEntity.php
  src/Util/ClassSourceManipulator.php
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/fixtures/add_entity_field/User_simple_ulid.php
  tests/Util/fixtures/add_entity_field/User_simple_uuid.php
Labels: Feature

#1146 [ci] we do not need to install flex globally anymore
  .github/workflows/ci.yaml
  appveyor.yml
Labels: Status: Needs Review, Minor

#940 [make:subscriber] Improve MakeSubscriber to use KernelEvents constant instead hardcoded event
  src/Maker/MakeSubscriber.php
  tests/Maker/MakeSubscriberTest.php
Labels: Feature, Status: Needs Review

#1150 [git-released] v1.44.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1155 [ci] fix failing php-cs-fixer test
  src/DependencyInjection/CompilerPass/MakeCommandRegistrationPass.php
Labels: Minor

#1153 [make:registration-form] Fix escape text-strings
  src/Maker/MakeRegistrationForm.php
Labels: Bug, Status: Reviewed

#1136 use method add() instead of [] in collection adder-method
  src/Util/ClassSourceManipulator.php
  tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/Client.php
  tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/User.php
  tests/Doctrine/fixtures/expected_overwrite/src/Entity/Client.php
  tests/Doctrine/fixtures/expected_overwrite/src/Entity/User.php
  tests/Doctrine/fixtures/expected_xml/src/Entity/UserXml.php
  tests/Util/fixtures/add_many_to_many_relation/User_simple_inverse.php
  tests/Util/fixtures/add_many_to_many_relation/User_simple_no_inverse.php
  tests/Util/fixtures/add_many_to_many_relation/User_simple_owning.php
  tests/Util/fixtures/add_one_to_many_relation/User_simple.php
  tests/Util/fixtures/add_one_to_many_relation/User_simple_orphan_removal.php
  tests/Util/fixtures/add_one_to_many_relation/User_with_use_statements.php
Labels: Feature

#1160 [git-released] v1.45.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1162 [ci] install sqlite3 in appveyor tests
  appveyor.yml
Labels: Minor
