Repository symfony/maker-bundle, pull requests merged in 2022-12, with the labels that each got.

#1248 [tests] use composer to require maker bundle in tests
  src/Test/MakerTestEnvironment.php
  src/Test/MakerTestRunner.php
  tests/Maker/MakeEntityTest.php
Labels: Status: Needs Review, Minor

#1253 [make:migration] Add link to new migration files
  src/Maker/MakeMigration.php
  src/Resources/config/makers.xml
  tests/Maker/MakeMigrationTest.php
Labels: Feature, Status: Reviewed

#1254 [make:migration] assert the output we care about
  tests/Maker/MakeMigrationTest.php
Labels: Minor

#1255 [tests] fix `http_method_override` deprecation
  tests/Doctrine/EntityRegeneratorTest.php
Labels: Minor

#1251 [make:*] use php-cs-fixer to style/lint all generated php templates
  composer.json
  src/Command/MakerCommand.php
  src/Generator.php
  src/Resources/bin/php-cs-fixer-v3.13.0.phar
  src/Resources/config/php-cs-fixer.config.php
  src/Resources/config/services.xml
  src/Resources/doc/index.rst
  src/Resources/test/.php_cs.test
  src/Test/MakerTestCase.php
  src/Test/MakerTestEnvironment.php
  src/Util/TemplateLinter.php
  tests/Command/MakerCommandTest.php
  tests/Maker/TemplateLinterTest.php
  tests/Util/TemplateLinterTest.php
  tests/fixtures/template-linter/php-cs-fixer.test.php
Labels: Feature, Status: Reviewed

#1263 [make:authenticator] doctrine/annotations not needed in tests
  tests/Maker/MakeAuthenticatorTest.php
  tests/fixtures/make-auth/annotations.yaml
Labels: Related Tests Pass, Minor

#1260 EntityRegenerator - no need to set annotations in tests
  src/Doctrine/EntityRegenerator.php
  tests/Doctrine/EntityRegeneratorTest.php
Labels: Related Tests Pass, Minor
