Repository symfony/maker-bundle, pull requests merged in 2022-11, with the labels that each got.

#1221 [make:voter] Set type for subject in Voter template
  src/Resources/skeleton/security/Voter.tpl.php
Labels: Feature, Status: Reviewed

#1226 [make:controller] replace repository method add by save
  src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
  src/Resources/skeleton/crud/test/Test.tpl.php
Labels: Bug, Status: Reviewed

#1227 [make:registration] Make router optional in MakeRegistrationForm constructor
  src/Maker/MakeRegistrationForm.php
  src/Resources/config/makers.xml
Labels: Bug, Status: Reviewed

#1232 [make:entity] Minor: Consistent output formatting
  src/Maker/MakeEntity.php
Labels: Bug, Status: Reviewed, Related Tests Pass

#1234 [git-released] v1.48.0
  CHANGELOG.md
Labels: Minor

#1237 [make:registration-form] Print registration form errors
  src/Resources/skeleton/registration/twig_template.tpl.php
Labels: Feature, Status: Reviewed

#1239 Improve error messages to show PHP & XML configurations are not supported
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
Labels: Feature

#1238 [make:*] improve output messages for Symfony CLI users
  src/Maker/MakeEntity.php
  src/Maker/MakeMigration.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Test/MakerTestEnvironment.php
  src/Test/MakerTestRunner.php
  src/Util/CliOutputHelper.php
  tests/Maker/MakeMigrationTest.php
  tests/Util/CliOutputHelperTest.php
Labels: Feature, Status: Reviewed

#1244 [make:security:form-login] new maker to use built in FormLogin
  src/Maker/Security/MakeFormLogin.php
  src/Resources/config/makers.xml
  src/Resources/help/security/MakeFormLogin.txt
  src/Resources/skeleton/security/formLogin/LoginController.tpl.php
  src/Resources/skeleton/security/formLogin/login_form.tpl.php
  src/Security/SecurityConfigUpdater.php
  tests/Maker/FunctionalTest.php
  tests/Maker/Security/MakeFormLoginTest.php
  tests/fixtures/security/make-form-login/LoginTest.php
  tests/fixtures/security/make-form-login/expected/LoginController.php
  tests/fixtures/security/make-form-login/expected/SecurityController.php
  tests/fixtures/security/make-form-login/expected/SecurityControllerWithoutLogout.php
  tests/fixtures/security/make-form-login/expected/login.html.twig
  tests/fixtures/security/make-form-login/expected/login_no_logout.html.twig
Labels: Feature, Status: Reviewed

#1245 Add tests for `SecurityConfigUpdater`
  src/Security/SecurityConfigUpdater.php
  tests/Security/SecurityConfigUpdaterTest.php
  tests/Security/yaml_fixtures/expected_form_login/form_login.yaml
  tests/Security/yaml_fixtures/expected_json_login/json_login.yaml
  tests/Security/yaml_fixtures/expected_logout/logout.yaml
Labels: Minor
