Repository symfony/maker-bundle, pull requests merged in 2022-04, with the labels that each got.

#1097 [ci] use composer 2.2 for Symfony 4.4 compat
  .github/workflows/ci.yaml
Labels: Minor

#1096 [git-released] v1.39.0
  CHANGELOG.md
Labels: Minor

#1098 drop symfony 4.4 support bump minimum Symfony version to 5.4.7
  .github/workflows/ci.yaml
  composer.json
  src/Doctrine/DoctrineHelper.php
  src/Generator.php
  src/Maker/MakeCrud.php
  src/Maker/MakeEntity.php
  src/Str.php
  src/Test/MakerTestRunner.php
Labels: Feature

#1101 [git-released] v1.40.0
  CHANGELOG.md
Labels: Minor

#1102 Lower symfony/finder & symfony/yaml requirements
  composer.json
Labels: Bug

#1105 [git-released] v1.40.1
  CHANGELOG.md
Labels: Minor

#1087 change signature method add/remove repository
  src/Resources/skeleton/doctrine/Repository.tpl.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php
Labels: Bug, Status: Reviewed

#903 [make:auth] use userIdentifier instead of username on login_form
  src/Resources/skeleton/authenticator/login_form.tpl.php
Labels: Bug, Status: Needs Work, Status: Reviewed

#872 Use object typehint when generating entities
  src/Util/ClassSourceManipulator.php
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/fixtures/add_entity_field/User_simple_object.php
  tests/Util/fixtures/add_entity_field/legacy/User_simple_object.php
Labels: Feature, Status: Needs Work, Status: Reviewed

#1104 [make:auth] drop guard support and legacy code cleanup
  src/Generator.php
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeUser.php
  src/Resources/skeleton/authenticator/EmptyAuthenticator.tpl.php
  src/Resources/skeleton/authenticator/EmptySecurityController.tpl.php
  src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php
  src/Resources/skeleton/authenticator/Security52EmptyAuthenticator.tpl.php
  src/Resources/skeleton/authenticator/Security52LoginFormAuthenticator.tpl.php
  src/Resources/skeleton/controller/Controller.tpl.php
  src/Resources/skeleton/crud/controller/Controller.tpl.php
  src/Resources/skeleton/registration/RegistrationController.tpl.php
  src/Security/InteractiveSecurityHelper.php
  src/Security/SecurityConfigUpdater.php
  tests/Maker/MakeAuthenticatorTest.php
  tests/Security/InteractiveSecurityHelperTest.php
  tests/Security/SecurityConfigUpdaterTest.php
  tests/Security/yaml_fixtures/expected_authenticator/empty_source.yaml
  tests/Security/yaml_fixtures/expected_authenticator/multiple_authenticators.yaml
  tests/Security/yaml_fixtures/expected_authenticator/security_52_empty_source.yaml
  tests/Security/yaml_fixtures/expected_authenticator/security_52_with_firewalls_and_logout.yaml
  tests/Security/yaml_fixtures/expected_authenticator/simple_security_source.yaml
  tests/Security/yaml_fixtures/expected_authenticator/simple_security_with_firewalls.yaml
  tests/Security/yaml_fixtures/expected_authenticator/simple_security_with_firewalls_and_authenticator.yaml
  tests/Security/yaml_fixtures/expected_authenticator/simple_security_with_firewalls_and_logout.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/empty_source_model_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/entity_username_no_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/model_email_password_existing_providers.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/model_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/model_username_no_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/security_52_complex_entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/5.3/simple_security_with_single_memory_provider_configured.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/empty_source_model_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/entity_username_no_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/model_email_password_existing_providers.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/model_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/model_username_no_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/security_52_complex_entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/security_52_entity_email_with_password.yaml
  tests/Security/yaml_fixtures/expected_user_class/legacy/simple_security_with_single_memory_provider_configured.yaml
  tests/Security/yaml_fixtures/source/empty_security.yaml
  tests/Security/yaml_fixtures/source/multiple_authenticators.yaml
  tests/Security/yaml_fixtures/source/multiple_providers_security.yaml
  tests/Security/yaml_fixtures/source/security_52_empty_security.yaml
  tests/Security/yaml_fixtures/source/security_52_with_firewalls_and_logout.yaml
  tests/Security/yaml_fixtures/source/simple_security.yaml
  tests/Security/yaml_fixtures/source/simple_security_with_firewalls.yaml
  tests/Security/yaml_fixtures/source/simple_security_with_firewalls_and_authenticator.yaml
  tests/Security/yaml_fixtures/source/simple_security_with_firewalls_and_logout.yaml
  tests/Security/yaml_fixtures/source/simple_security_with_single_memory_provider_configured.yaml
Labels: Feature, Status: Needs Review
