Repository symfony/maker-bundle, pull requests merged in 2022-09, with the labels that each got.

#1179 [ci] several fixes
  src/Maker/MakeResetPassword.php
  src/Test/MakerTestKernel.php
  src/Test/MakerTestRunner.php
  src/Util/ComposeFileManipulator.php
Labels: Minor

#1163 fix attribute support in symfony 4.4 applications
  src/Doctrine/DoctrineHelper.php
Labels: Bug

#1181 [4.4] handle legacy Doctrine Persistance AnnotationDriver
  .github/workflows/ci.yaml
  appveyor.yml
  src/Doctrine/DoctrineHelper.php
  src/Maker/MakeResetPassword.php
  src/Maker/MakeUser.php
  src/Test/MakerTestRunner.php
  src/Util/ComposeFileManipulator.php
  src/Util/YamlSourceManipulator.php
  tests/Maker/MakeMessengerMiddlewareTest.php
  tests/Security/SecurityControllerBuilderTest.php
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/MakerFileLinkFormatterTest.php
  tests/Util/YamlSourceManipulatorTest.php
Labels: Bug

#1182 [release] v1.39.1
  CHANGELOG.md
Labels: Minor

#1019 Add `make:twig-component` maker
  src/Maker/MakeTwigComponent.php
  src/Resources/config/makers.xml
  src/Resources/skeleton/twig/Component.tpl.php
  src/Resources/skeleton/twig/LiveComponent.tpl.php
  src/Resources/skeleton/twig/component_template.tpl.php
  tests/Maker/MakeTwigComponentTest.php
  tests/fixtures/make-twig-component/tests/it_generates_live_component.php
  tests/fixtures/make-twig-component/tests/it_generates_twig_component.php
Labels: Feature, Status: Needs Work

#1200 [ci] handle Mercure recipe change
  .github/workflows/ci.yaml
  tests/Maker/MakeEntityTest.php
Labels: Minor

#1201 [ci] handle reset-password 8.1.10 version constraint
  src/Test/MakerTestDetails.php
  tests/Maker/MakeResetPasswordTest.php
Labels: Related Tests Pass, Minor

#1202 [reset-password] use higher level "options" in ChangePasswordFormType.tpl.php
  src/Resources/skeleton/resetPassword/ChangePasswordFormType.tpl.php
Labels: Feature, Status: Reviewed

#1199 [make:entity] fix compatibility with api-platform 3.0
  src/Maker/MakeEntity.php
  tests/Maker/MakeEntityTest.php
Labels: Bug

#1204 [make:crud] use save instead of add repository methods
  src/Resources/skeleton/crud/controller/Controller.tpl.php
  src/Resources/skeleton/doctrine/Repository.tpl.php
  src/Util/TemplateComponentGenerator.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php
  tests/fixtures/make-crud/SweetFoodRepository.php
  tests/fixtures/make-crud/expected/WithCustomRepository.php
Labels: Feature, Status: Reviewed, Related Tests Pass

#1176 [make:entity] Fix error while making blob in entity
  src/Util/ClassSourceManipulator.php
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/fixtures/add_setter/User_simple_null_type.php
Labels: Bug, Status: Reviewed

#1206 [git-released] v1.40.0
  CHANGELOG.md
Labels: Minor

#1209 [make:crud] use save instead of add in `upgradePassword`
  src/Resources/skeleton/doctrine/Repository.tpl.php
Labels: Bug

#1210 [make:serializer] use empty string in str_replace
  src/Resources/skeleton/serializer/Normalizer.tpl.php
Labels: Bug, Related Tests Pass

#1211 [make:twig-extension] Change folder for Twig Extension
  src/Maker/MakeTwigExtension.php
Labels: Feature, Status: Reviewed
