Repository symfony/maker-bundle, pull requests merged in 2023-05, with the labels that each got.

#1304 [ci] fix stalled CI runs
  .github/workflows/ci.yaml
Labels: Minor

#1284 [tests] handle postgres v15
  .github/workflows/ci.yaml
  src/Test/MakerTestRunner.php
Labels: Minor

#1305 ignore platform requirements when linting templates with make:*
  src/Util/TemplateLinter.php
Labels: Bug

#1307 [make:twig-component] handle upstream changes to how live components are rendered
  tests/fixtures/make-twig-component/tests/it_generates_live_component.php
Labels: Minor

#1290 [make:registration-form] avoid using internal method get from Request
  src/Resources/skeleton/registration/RegistrationController.tpl.php
Labels: Bug, Status: Reviewed, Related Tests Pass

#1272 [make:crud] render or renderForm - Avoid deprecations in 6.2
  src/Maker/MakeCrud.php
  src/Resources/skeleton/crud/controller/Controller.tpl.php
Labels: Feature, Status: Reviewed, Related Tests Pass

#1309 Apply `get_class_to_class_keyword` PHP-CS-Fixer rule
  src/Resources/skeleton/doctrine/Repository.tpl.php
  src/Resources/skeleton/security/UserProvider.tpl.php
Labels: Feature, Status: Reviewed, Related Tests Pass

#1311 bump phpunit-bridge version constraint
  composer.json
Labels: Bug, Related Tests Pass, Status: Needs Review
