Repository symfony/maker-bundle, pull requests merged in 2023-01, with the labels that each got.

#1264 [make:controller] doctrine/annotations is not needed
  src/Maker/MakeController.php
  tests/Maker/MakeAuthenticatorTest.php
  tests/Maker/MakeControllerTest.php
  tests/fixtures/make-auth/annotations.yaml
  tests/fixtures/router-annotations.yaml
Labels: Bug, Status: Needs Review

#1267 [make:registration-form] use route attributes for test routes
  tests/Maker/MakeRegistrationFormTest.php
  tests/fixtures/make-registration-form/standard_setup/src/Controller/TestingController.php
Labels: Minor

#1261 [make:registration-form] use UniqueEntity attribute instead of annotation
  src/Maker/MakeRegistrationForm.php
  src/Util/ClassDetails.php
  tests/Util/ClassDetailsTest.php
Labels: Feature, Related Tests Pass, Status: Needs Review

#1268 [make:security:form-login] configure route attributes for 5.4
  tests/Maker/Security/MakeFormLoginTest.php
Labels: Minor

#1262 [make:reset-password] doctrine/annotations are not needed
  src/Maker/MakeResetPassword.php
  tests/Maker/MakeResetPasswordTest.php
  tests/fixtures/make-reset-password/tests/it_generates_with_normal_setup.php
Labels: Feature

#1265 [make:crud] Make sensio/framework-extra-bundle an optional dependency
  src/Maker/MakeCrud.php
Labels: Feature, Status: Reviewed, Related Tests Pass
