Repository symfony/maker-bundle, pull requests merged in 2024-04, with the labels that each got.

#1499 [make:*] add docBlock return types for non-internal makers
  src/Maker/MakeFixtures.php
  src/Maker/MakeMigration.php
  src/Maker/MakeValidator.php
Labels: Feature

#1501 fix exception message when twigcs is not installed
  src/Test/MakerTestEnvironment.php
Labels: Minor

#1500 [make:registration] add missing property types
  src/Maker/MakeRegistrationForm.php
Labels: Minor

#1503 [make:entity] ask() doesnt accept "int" only "string"
  src/Maker/MakeEntity.php
Labels: Minor

#1502 [make:*] additional type improvements
  src/Maker/AbstractMaker.php
  src/Maker/MakeListener.php
  src/Maker/MakeMigration.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeTest.php
Labels: Feature

#1504 [make:stimulus-controller] use named arguments where possible
  src/Maker/MakeStimulusController.php
Labels: Minor

#1506 [make:stimulus-controller] more typehints
  src/Maker/MakeStimulusController.php
Labels: Minor

#1507 [make:authenticator] more typehints / types
  src/Maker/MakeAuthenticator.php
Labels: Minor

#1498 [ci] implement phpstan for static analysis of the codebase
  .github/workflows/ci-linux.yaml
  .github/workflows/ci-static-analysis.yaml
  phpstan.dist.neon
  src/Maker/MakeEntity.php
  src/Maker/MakeUser.php
  tests/Maker/FunctionalTest.php
  tests/Maker/MakeEntityTest.php
  tests/Maker/MakeFormTest.php
  tests/Maker/MakeMessageTest.php
  tests/Maker/MakeMessengerMiddlewareTest.php
  tests/Maker/MakeSerializerEncoderTest.php
  tests/Maker/MakeTwigExtensionTest.php
  tests/Maker/MakeUnitTestTest.php
  tests/Maker/MakeValidatorTest.php
  tests/Maker/MakeVoterTest.php
  tools/phpstan/composer.json
  tools/phpstan/includes/.gitignore
  tools/phpstan/includes/composer.json
Labels: Minor

#1491 [make:webhook] Add new command for Symfony's Webhook Component
  src/Maker/Common/InstallDependencyTrait.php
  src/Maker/MakeWebhook.php
  src/Resources/config/makers.xml
  src/Resources/help/MakeWebhook.txt
  src/Resources/skeleton/webhook/RequestParser.tpl.php
  src/Resources/skeleton/webhook/WebhookConsumer.tpl.php
  src/Test/MakerTestEnvironment.php
  tests/Maker/MakeWebhookTest.php
  tests/RegexTest.php
  tests/fixtures/make-webhook/RemoteServiceRequestParser.php
  tests/fixtures/make-webhook/RemoteServiceWebhookConsumer.php
  tests/fixtures/make-webhook/webhook.yaml
  tools/phpstan/includes/composer.json
Labels: Feature, Status: Reviewed

#1510 [release] v1.58.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1512 [make:webhook] Rephrase comments to be more explicit + minor improvement of generated code
  src/Resources/skeleton/webhook/RequestParser.tpl.php
  tests/fixtures/make-webhook/RemoteServiceRequestParser.php
Labels: Feature

#1511 [make:entity] helper message with two classes having the same name under different namespaces
  src/Maker/MakeEntity.php
  src/Str.php
  tests/Maker/MakeEntityTest.php
  tests/StrTest.php
  tests/fixtures/make-entity/entities/attributes/Friend/User-sub-namespace.php
Labels: Status: Reviewed

#1516 [common] add missing class header
  src/Maker/Common/InstallDependencyTrait.php
Labels: Bug

#1518 [make:registration] add `bool` type to User::isVerified
  src/Maker/MakeRegistrationForm.php
  tests/Maker/MakeRegistrationFormTest.php
Labels: Feature, Status: Needs Review

#1519 [make:registration] use "User" type in `EmailVerifier::class`
  src/Maker/MakeRegistrationForm.php
  src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
Labels: Feature, Status: Needs Review

#1521 [make:reset-password] improve types for static analysis in userland
  src/Maker/MakeResetPassword.php
  src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
Labels: Feature

#1497 [make:*] add ability to generate tests
  src/Maker/Common/CanGenerateTestsTrait.php
  src/Maker/MakeCrud.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Resources/config/makers.xml
  src/Resources/help/_WithTests.txt
  src/Resources/skeleton/registration/Test.WithVerify.tpl.php
  src/Resources/skeleton/registration/Test.WithoutVerify.tpl.php
  src/Resources/skeleton/resetPassword/Test.ResetPasswordController.tpl.php
  tests/Maker/MakeRegistrationFormTest.php
  tests/Maker/MakeResetPasswordTest.php
  tests/fixtures/make-reset-password/src/Controller/FixtureController.php
Labels: Feature, Status: Needs Review

#1522 [make:security:custom] create a custom authenticator
  src/Maker/Security/MakeCustomAuthenticator.php
  src/Resources/config/makers.xml
  src/Resources/help/security/MakeCustom.txt
  src/Resources/skeleton/security/custom/Authenticator.tpl.php
  tests/Maker/Security/MakeCustomAuthenticatorTest.php
  tests/fixtures/security/make-custom-authenticator/expected/FixtureAuthenticator.php
Labels: Feature

#1525 [make:serializer:encoder] fix interface signature mismatch in template
  src/Maker/MakeSerializerEncoder.php
  src/Resources/skeleton/serializer/Encoder.tpl.php
  tests/Maker/MakeSerializerEncoderTest.php
Labels: Bug

#1520 [make:entity] Simplify repository PHPDoc removes method annotations
  src/Resources/skeleton/doctrine/Repository.tpl.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/UserRepository.php
  tests/Doctrine/fixtures/expected_xml/src/Repository/XOtherRepository.php
  tests/fixtures/make-crud/SweetFoodRepository.php
Labels: Feature, Status: Reviewed

#1515 [make:security:form-login] add ability to generate tests
  src/Maker/Security/MakeFormLogin.php
  src/Resources/skeleton/security/formLogin/Test.LoginController.tpl.php
  tests/Maker/Security/MakeFormLoginTest.php
  tests/fixtures/security/make-form-login/FixtureController.php
Labels: Feature, Status: Needs Review

#1523 [make:auth] deprecate command
  src/Maker/MakeAuthenticator.php
  tests/Maker/MakeAuthenticatorTest.php
Labels: Feature

#1526 [release] v1.59.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor
