Repository symfony/maker-bundle, pull requests merged in 2024-08, with the labels that each got.

#1576 [ci] allow template linter tests on OSX (Darwin)
  src/Util/TemplateLinter.php
  tests/Util/TemplateLinterTest.php
Labels: Status: Reviewed, Minor

#1562 [docs] document new config values
  .doctor-rst.yaml
  .gitattributes
  .github/workflows/ci-docs.yaml
  .gitignore
  README.md
  _docs_build/build.php
  _docs_build/composer.json
  _docs_build/composer.lock
  _docs_build/redirection_map
  _docs_build/spelling_word_list.txt
  src/Resources/doc/index.rst
Labels: Related Tests Pass, Status: Needs Review, Minor

#1583 [make:crud] Remove `/` from from index action URL
  src/Resources/skeleton/crud/controller/Controller.tpl.php
  src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
  src/Util/TemplateComponentGenerator.php
  tests/fixtures/make-crud/expected/WithCustomRepository.php
  tests/fixtures/make-crud/tests/it_generates_basic_crud.php
  tests/fixtures/make-crud/tests/it_generates_crud_with_custom_controller.php
  tests/fixtures/make-crud/tests/it_generates_crud_with_custom_root_namespace.php
Labels: Feature, Status: Reviewed

#1586 [ci] handle deprecations
  tests/Doctrine/EntityRegeneratorTest.php
Labels: Minor

#1585 [release] v1.61.0
  CHANGELOG.md
Labels: Status: Reviewed, Related Tests Pass, Minor
