Repository symfony/maker-bundle, pull requests merged in 2024-01, with the labels that each got.

#1417 Compatibility to dependency php parser v5
  .github/workflows/ci.yaml
  composer.json
  src/Security/SecurityControllerBuilder.php
  src/Util/ClassSourceManipulator.php
  src/Util/PrettyPrinter.php
  tests/Util/ClassSourceManipulatorTest.php
Labels: Feature

#1420 [ci] handle postgres 16 recipe support in .env
  src/Test/MakerTestRunner.php
Labels: Minor

#1403 Doctrine make:fixtures - Remove extra semicolon
  src/Resources/skeleton/doctrine/Fixtures.tpl.php
Labels: Bug

#1342 fix missing blank space in Repository.tpl.php
  src/Resources/skeleton/doctrine/Repository.tpl.php
Labels: Bug, Status: Reviewed

#1419 [make:controller] remove CodeExtension::getFileLink() call when generating twig templates
  src/GeneratorTwigHelper.php
  src/Resources/skeleton/controller/twig_template.tpl.php
Labels: Bug, Status: Reviewed, Related Tests Pass

#1426 [ci] enable skipped Symfony 7 tests
  tests/Maker/MakeEntityTest.php
  tests/Maker/MakeFixturesTest.php
  tests/Maker/MakeFunctionalTestTest.php
  tests/Maker/MakeRegistrationFormTest.php
  tests/Maker/MakeResetPasswordTest.php
  tests/Maker/MakeStimulusControllerTest.php
  tests/Maker/MakeTestTest.php
  tests/Maker/MakeTwigComponentTest.php
Labels: Minor

#1396 Update README.md
  README.md
Labels: Status: Reviewed, Minor
