Repository symfony/maker-bundle, pull requests merged in 2024-06, with the labels that each got.

#1568 [make:schedule] Add transport name for attribute
  src/Maker/MakeSchedule.php
  src/Resources/skeleton/scheduler/Schedule.tpl.php
  tests/Maker/MakeScheduleTest.php
  tests/fixtures/make-schedule/expected/DefaultScheduleWithTransportName.php
Labels: Feature, Status: Reviewed

#1569 [make:twig-component] Fix generated twig file location
  src/Maker/MakeTwigComponent.php
  tests/Maker/MakeTwigComponentTest.php
Labels: Bug, Status: Reviewed

#1570 [release] v1.60.0
  CHANGELOG.md
Labels: Minor

#1549 [make:registration-form] improve generated types for phpstan
  src/Resources/skeleton/registration/RegistrationController.tpl.php
  src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
  tests/fixtures/make-registration-form/expected/RegistrationControllerCustomAuthenticator.php
  tests/fixtures/make-registration-form/expected/RegistrationControllerFormLogin.php
  tests/fixtures/make-registration-form/expected/RegistrationControllerNoLogin.php
Labels: Feature, Status: Reviewed

#1548 [make:reset-password] improve generated typehints for phpstan
  src/Resources/skeleton/resetPassword/ResetPasswordController.tpl.php
  tests/Maker/MakeResetPasswordTest.php
Labels: Feature, Status: Reviewed

#1550 [make:user] fix `getPassword()` return type in certain instance with `PasswordAuthenticatedUserInterface`
  src/Security/UserClassBuilder.php
  tests/Security/fixtures/expected/UserEntityWithEmailAsIdentifier.php
  tests/Security/fixtures/expected/UserEntityWithPassword.php
  tests/Security/fixtures/expected/UserEntityWithUser_IdentifierAsIdentifier.php
  tests/Security/fixtures/expected/UserModelWithEmailAsIdentifier.php
  tests/Security/fixtures/expected/UserModelWithPassword.php
Labels: Bug, Status: Reviewed

#1571 [make:twig-component] Improve `make:twig-component` by reading the configuration file
  src/Maker/MakeTwigComponent.php
  src/Resources/config/makers.xml
  tests/Maker/MakeTwigComponentTest.php
  tests/fixtures/make-twig-component/custom_twig_component.yaml
Labels: Feature, Status: Reviewed

#1573 [make:twig-component] Fix config file in error messages
  src/Maker/MakeTwigComponent.php
Labels: Bug, Status: Reviewed
