Repository symfony/maker-bundle, pull requests merged in 2024-05, with the labels that each got.

#1532 [make:auth] only fire deprecation when command is called
  src/Maker/MakeAuthenticator.php
Labels: Bug, Status: Reviewed

#1538 [release] v1.59.1
  CHANGELOG.md
Labels: Minor

#1547 [make:validator] phpstan types
  src/Resources/skeleton/validator/Constraint.tpl.php
  src/Resources/skeleton/validator/Validator.tpl.php
Labels: Feature, Status: Reviewed

#1546 [make:message] phpstan types
  src/Resources/skeleton/message/MessageHandler.tpl.php
Labels: Feature, Status: Reviewed

#1544 [make:webhook] phpstan types and single quotes
  src/Maker/MakeWebhook.php
  src/Resources/skeleton/webhook/RequestParser.tpl.php
Labels: Feature, Status: Reviewed

#1543 [dx] make it easier to use tooling for devs
  composer.json
Labels: Feature, DX, Status: Needs Review

#1545 [make:crud] use `getString()` instead of `get()` for csrf token
  src/Resources/skeleton/crud/controller/Controller.tpl.php
  tests/fixtures/make-crud/expected/WithCustomRepository.php
Labels: Feature, Status: Reviewed

#1560 [debug] null string literal to null for process timeout
  src/Test/MakerTestProcess.php
Labels: DX, Minor

#1559 [make:entity] fix indentation in broadcast_twig_template.tpl.php
  src/Resources/skeleton/doctrine/broadcast_twig_template.tpl.php
Labels: Bug

#1534 [make:entity] add enum support
  src/Maker/MakeEntity.php
  src/Util/ClassSource/Model/ClassProperty.php
  src/Util/ClassSourceManipulator.php
  src/Validator.php
  tests/Maker/MakeEntityTest.php
  tests/fixtures/make-entity/entities/attributes/Enum/Role-basic.php
Labels: Feature, Status: Needs Work

#1496 [make:entity] confirm to allow non-ascii char's in entity names
  src/Maker/MakeEntity.php
  tests/Maker/MakeEntityTest.php
Labels: Bug, Status: Reviewed

#1564 [ci] test against 7.1
  .github/workflows/ci-linux.yaml
Labels: Minor

#1563 [tests] dont sign commits in tests
  src/Test/MakerTestEnvironment.php
Labels: DX, Minor

#1565 [make:controller] add tests to confirm twig templates generated
  src/Resources/help/MakeController.txt
  tests/Maker/MakeControllerTest.php
Labels: Minor
