Repository symfony/maker-bundle, pull requests merged in 2024-03, with the labels that each got.

#1463 [make:serializer:normalizer] stop using CacheableSupportsMethodInterface
  src/Maker/MakeSerializerNormalizer.php
  src/Resources/config/makers.xml
  src/Resources/skeleton/serializer/Normalizer.tpl.php
  tests/Maker/MakeSerializerNormalizerTest.php
  tests/fixtures/make-serializer-normalizer/EntityFixture.php
  tests/fixtures/make-serializer-normalizer/EntityFixtureNormalizer.php
  tests/fixtures/make-serializer-normalizer/FooBarNormalizer.php
Labels: Feature, Status: Reviewed

#1243 [make:registration] drop guard authentication support
  src/Maker/MakeRegistrationForm.php
  src/Resources/skeleton/registration/RegistrationController.tpl.php
  src/Security/InteractiveSecurityHelper.php
  src/Security/Model/Authenticator.php
  src/Security/Model/AuthenticatorType.php
  tests/Maker/MakeRegistrationFormTest.php
  tests/Security/InteractiveSecurityHelperTest.php
  tests/fixtures/make-registration-form/expected/RegistrationControllerCustomAuthenticator.php
  tests/fixtures/make-registration-form/expected/RegistrationControllerFormLogin.php
  tests/fixtures/make-registration-form/expected/RegistrationControllerNoLogin.php
Labels: Feature, Status: Needs Review

#1413 [DoctrineHelper] handle property type for custom doctrine type
  src/Doctrine/DoctrineHelper.php
Labels: Feature, Status: Reviewed

#1469 [make:form] fix generated field options_code indentation
  src/Resources/config/php-cs-fixer.config.php
  src/Util/TemplateLinter.php
Labels: Bug, Status: Reviewed

#516 [make:migration] add ability to specify a configuration file
  src/Maker/MakeMigration.php
Labels: Feature, Status: Needs Review

#1472 [make:migration] --configuration is available in all versions
  src/Maker/MakeMigration.php
Labels: Bug

#1471 [release] v1.56.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1473 [make:*] use `getPayload()` instead of accessing `request` on Request objects
  src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php
  src/Resources/skeleton/crud/controller/Controller.tpl.php
  tests/fixtures/make-crud/expected/WithCustomRepository.php
Labels: Feature, Status: Reviewed

#1477 [make:message] Modernize Messenger\Message class, use PHP8 features
  src/Resources/skeleton/message/Message.tpl.php
Labels: Feature, Status: Reviewed

#1474 [make:entity] Prevent entity name from having an accent
  src/Maker/MakeEntity.php
  tests/Maker/MakeEntityTest.php
Labels: Feature, Status: Reviewed

#1475 [make:user] better exception msg for non-attribute mapping entities
  src/Doctrine/DoctrineHelper.php
Labels: Feature

#1483 do not include dev files in release
  .gitattributes
Labels: Minor

#1464 [make:registration-form] use validateEmailConfirmationFromRequest() when verifying emails
  src/Maker/MakeRegistrationForm.php
  src/Resources/skeleton/registration/RegistrationController.tpl.php
  src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
Labels: Feature, Status: Waiting Feedback

#1484 [make:auth] use `getString()` instead of `get()`
  src/Resources/skeleton/authenticator/LoginFormAuthenticator.tpl.php
Labels: Feature, Status: Reviewed

#1485 [ci] run php-cs-fixer
  src/Maker/MakeCrud.php
  src/Maker/MakeRegistrationForm.php
  src/Test/MakerTestEnvironment.php
  tests/Maker/MakeControllerTest.php
  tests/Util/ClassSourceManipulatorTest.php
Labels: Minor

#1329 Add support for generating UUID id fields in entities
  src/Doctrine/EntityClassGenerator.php
  src/Maker/Common/UidTrait.php
  src/Maker/MakeEntity.php
  src/Maker/MakeResetPassword.php
  src/Maker/MakeUser.php
  src/Resources/skeleton/doctrine/Entity.tpl.php
  tests/Maker/FunctionalTest.php
  tests/Maker/MakeEntityTest.php
  tests/Maker/MakeResetPasswordTest.php
  tests/Maker/MakeUserTest.php
  tests/fixtures/make-user/tests/it_generates_entity_with_password_and_uuid.php
Labels: Feature, Status: Needs Work

#1488 [make:*] allow the option to use ULID's for entity id's
  src/Doctrine/EntityClassGenerator.php
  src/Maker/Common/EntityIdTypeEnum.php
  src/Maker/Common/UidTrait.php
  src/Maker/MakeEntity.php
  src/Maker/MakeResetPassword.php
  src/Maker/MakeUser.php
  src/Resources/help/_WithUid.txt
  src/Resources/skeleton/doctrine/Entity.tpl.php
  tests/Maker/MakeEntityTest.php
  tests/Maker/MakeResetPasswordTest.php
  tests/Maker/MakeUserTest.php
  tests/fixtures/make-user/tests/it_generates_entity_with_password_and_ulid.php
Labels: Feature

#1490 [make:entity] Fix a small typo in a make:entity error message
  src/Maker/MakeEntity.php
Labels: Bug, Status: Reviewed

#1486 [make:entity] Fix exception message if mercure bundle not found with --broadcast
  src/Maker/MakeEntity.php
Labels: Bug, Status: Reviewed

#1489 [release] v1.57.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1493 [make:entity] managing keyword prefixes (is, has) for boolean properties getters
  src/Resources/skeleton/verifyEmail/EmailVerifier.tpl.php
  src/Util/ClassSourceManipulator.php
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/fixtures/add_getter/User_bool_begins_with_has.php
  tests/Util/fixtures/add_getter/User_bool_begins_with_is.php
  tests/Util/fixtures/add_setter/User_bool_begins_with_is.php
Labels: Feature, Status: Reviewed

#1494 [ysm] improve type declarations
  src/Util/YamlSourceManipulator.php
Labels: Status: Needs Work, Minor

#1487 [make:schedule] a new command for creating recurring Symfony Schedules
  src/Maker/MakeSchedule.php
  src/Resources/config/makers.xml
  src/Resources/help/MakeScheduler.txt
  src/Resources/skeleton/scheduler/Schedule.tpl.php
  tests/Maker/MakeScheduleTest.php
  tests/fixtures/make-schedule/expected/DefaultScheduleEmpty.php
  tests/fixtures/make-schedule/expected/MyScheduleEmpty.php
  tests/fixtures/make-schedule/expected/MyScheduleWithMessage.php
  tests/fixtures/make-schedule/standard_setup/src/Message/MessageFixture.php
Labels: Feature, Status: Needs Review

#1219 [make:entity] Add PHPDoc var type for Collections
  src/Util/ClassSourceManipulator.php
  tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/Client.php
  tests/Doctrine/fixtures/expected_no_overwrite/src/Entity/User.php
  tests/Doctrine/fixtures/expected_overwrite/src/Entity/Client.php
  tests/Doctrine/fixtures/expected_overwrite/src/Entity/User.php
  tests/Doctrine/fixtures/expected_xml/src/Entity/UserXml.php
  tests/Doctrine/fixtures/source_project/src/Entity/Client.php
  tests/Doctrine/fixtures/source_project/src/Entity/User.php
  tests/Util/fixtures/add_many_to_many_relation/User_simple_inverse.php
  tests/Util/fixtures/add_many_to_many_relation/User_simple_no_inverse.php
  tests/Util/fixtures/add_many_to_many_relation/User_simple_owning.php
  tests/Util/fixtures/add_one_to_many_relation/User_simple.php
  tests/Util/fixtures/add_one_to_many_relation/User_simple_orphan_removal.php
  tests/Util/fixtures/add_one_to_many_relation/User_with_use_statements.php
  tests/Util/fixtures/add_one_to_many_relation/legacy/User_simple.php
  tests/Util/fixtures/add_one_to_many_relation/legacy/User_simple_orphan_removal.php
  tests/Util/fixtures/add_one_to_many_relation/legacy/User_with_use_statements.php
  tests/fixtures/make-entity/regenerate/attributes/src/Entity/User.php
  tests/fixtures/make-form/SourFood.php
Labels: Feature, Status: Reviewed

#1495 [ci] minor refactor to allow for more regex tests
  tests/RegexTest.php
Labels: Minor

#1476 [ysm] handle linebreak followed by an immediate root-level comment
  src/Util/YamlSourceManipulator.php
  tests/Util/YamlSourceManipulatorTest.php
  tests/Util/yaml_fixtures/new_line_with_root_level_comment.test
Labels: Bug
