Repository symfony/maker-bundle, pull requests merged in 2024-09, with the labels that each got.

#1590 [make:validator] drop annotation support in constraint
  src/Resources/skeleton/validator/Constraint.tpl.php
Labels: Feature

#1593 [docs] ignore composer lock file
  _docs_build/.gitignore
  _docs_build/composer.lock
Labels: Minor

#1598 [ci] temp. skip API Platform tests - recipe conflict
  tests/Maker/MakeEntityTest.php
Labels: Minor

#1575 [make:*] Use a PHP-CS-Fixer shim rather than an external PHAR
  composer.json
  src/Resources/bin/php-cs-fixer-v3.49.0.phar
  src/Resources/config/services.xml
  src/Util/TemplateLinter.php
  tests/Command/MakerCommandTest.php
  tests/Maker/TemplateLinterTest.php
  tests/Util/TemplateLinterTest.php
  tests/fixtures/make-serializer-normalizer/EntityFixtureNormalizer.php
  tests/fixtures/make-serializer-normalizer/FooBarNormalizer.php
  tests/fixtures/make-validator/expected/FooBar.php
  tests/fixtures/make-voter/expected/FooBarVoter.php
  tests/fixtures/make-voter/expected/not_final_FooBarVoter.php
Labels: Feature, Status: Reviewed

#1602 [make:controller] add tests for command argument names
  .github/workflows/ci-windows.yaml
  phpunit.xml.dist
  tests/Maker/MakeControllerTest.php
Labels: Minor

#1588 [make:controller] generate final controller class
  src/Generator.php
  src/Maker/MakeController.php
  src/Resources/skeleton/controller/Controller.tpl.php
  src/Util/ClassSource/Model/ClassData.php
  tests/Maker/MakeControllerTest.php
  tests/Util/ClassSource/ClassDataTest.php
  tests/fixtures/make-controller/expected/FinalController.php
  tests/fixtures/make-controller/expected/FinalControllerWithTemplate.php
  tests/fixtures/make-controller/tests/it_generates_a_controller.php
  tests/fixtures/make-controller/tests/it_generates_a_controller_with_twig.php
  tests/fixtures/make-controller/tests/it_generates_an_invokable_controller.php
Labels: Feature, Status: Needs Review

#1603 [make:controller] add ability to create controller with tests
  src/Maker/MakeController.php
  src/Resources/skeleton/controller/test/Test.tpl.php
  tests/Maker/MakeControllerTest.php
Labels: Feature

#1604 [make:controller] maker housekeeping
  src/Maker/MakeController.php
Labels: Minor

#1596 [tests] Fix double slashes in tmp PHPUnit path
  src/Test/MakerTestRunner.php
Labels: Bug, Status: Reviewed

#1597 [make:crud] name repository variable with entity prefix when generating tests
  src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
Labels: Feature, Status: Reviewed

#1514 replace Bundle with the new AbstractBundle class
  .symfony.bundle.yaml
  _docs_build/build.php
  config/makers.xml
  config/php-cs-fixer.config.php
  config/services.xml
  docs/index.rst
  src/DependencyInjection/Configuration.php
  src/DependencyInjection/MakerExtension.php
  src/MakerBundle.php
  src/Util/TemplateLinter.php
Labels: Status: Needs Review, Minor
