Repository symfony/maker-bundle, pull requests merged in 2024-02, with the labels that each got.

#1427 [git-released] v1.53.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1421 [make:*] drop Symfony 6.3 support
  .github/workflows/ci.yaml
  composer.json
  src/Test/MakerTestEnvironment.php
Labels: Feature, Status: Needs Review

#1425 [dx] require >= PHPUnit 9.6, update phpunit schema, deprecate skipOnSymfony7()
  .gitignore
  phpunit.xml.dist
  src/Test/MakerTestCase.php
  src/Test/MakerTestDetails.php
  tests/Maker/MakeEntityTest.php
Labels: Feature, Status: Reviewed, Related Tests Pass

#1428 [make:*] use Routing\Attribute\* instead of Routing\Annotation\*
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeController.php
  src/Maker/MakeCrud.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Maker/Security/MakeFormLogin.php
  src/Security/SecurityControllerBuilder.php
  tests/Security/fixtures/expected/SecurityController_login.php
  tests/Security/fixtures/expected/SecurityController_login_logout.php
  tests/Security/fixtures/expected/SecurityController_logout.php
  tests/Util/ClassSourceManipulatorTest.php
  tests/Util/UseStatementGeneratorTest.php
  tests/Util/fixtures/add_method/Controller_with_action.php
  tests/fixtures/make-crud/expected/WithCustomRepository.php
  tests/fixtures/make-registration-form/standard_setup/src/Controller/TestingController.php
  tests/fixtures/security/make-form-login/expected/LoginController.php
  tests/fixtures/security/make-form-login/expected/SecurityController.php
  tests/fixtures/security/make-form-login/expected/SecurityControllerWithoutLogout.php
Labels: Feature, Status: Needs Work

#1430 [ci] use sqlite in tests
  .github/workflows/ci.yaml
  appveyor.yml
  phpunit.xml.dist
Labels: Minor

#1433 [make:crud] Remove extra dot
  src/Maker/MakeCrud.php
Labels: Bug, Status: Reviewed

#1435 [make:*] fix bundled php-cs-fixer not working on windows
  src/Util/TemplateLinter.php
Labels: Bug, Related Tests Pass

#1432 [make:controller] use promoted parameter
  src/Maker/MakeController.php
Labels: Feature, Status: Reviewed

#1424 [ci] windows tests on GitHub actions
  .github/workflows/ci-linux.yaml
  .github/workflows/ci-windows.yaml
  phpunit.xml.dist
  src/Test/MakerTestEnvironment.php
  tests/Maker/MakeFunctionalTestTest.php
  tests/Maker/MakeTestTest.php
  tests/RegexTest.php
Labels: Status: Reviewed, Minor

#1436 [ci] remove appveyor runs
  appveyor.yml
Labels: Status: Reviewed, Minor

#1441 [git-released] v1.54.0
  CHANGELOG.md
Labels: Status: Needs Review, Minor

#1434 [ci] php-cs-fixer fix && review
  .php-cs-fixer.dist.php
  src/Command/MakerCommand.php
  src/Doctrine/DoctrineHelper.php
  src/Generator.php
  src/InputAwareMakerInterface.php
  src/Maker/AbstractMaker.php
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeEntity.php
  src/Maker/MakeTest.php
  src/Maker/MakeUser.php
  src/Renderer/FormTypeRenderer.php
  src/Security/InteractiveSecurityHelper.php
  src/Security/UserClassBuilder.php
  src/Util/YamlSourceManipulator.php
  src/Validator.php
  tests/Util/AutoloaderUtilTest.php
  tests/Util/ClassSourceManipulatorTest.php
Labels: Minor

#1444 [make:command] deprecate passing PhpCompatUtil to the constructor
  src/Maker/MakeCommand.php
  src/Resources/config/makers.xml
Labels: Feature, Deprecation

#1443 [make:controller] deprecate passing PhpCompatUtil to the constructor
  src/Maker/MakeController.php
  src/Resources/config/makers.xml
Labels: Feature, Deprecation

#1431 [ci] handle doctrine lazy ghost deprecation in entity regen tests
  tests/Doctrine/EntityRegeneratorTest.php
Labels: Minor

#1442 [ci] re-enable mercure tests on linux
  .github/workflows/ci-linux.yaml
Labels: Minor

#1448 [make:entity] only show supported types in cli wizard
  src/Maker/MakeEntity.php
  tests/Maker/MakeEntityTest.php
Labels: Bug, Status: Reviewed

#1449 [tests] fix broken assignment operator - addExtraDependencies()
  src/Test/MakerTestDetails.php
  tests/Test/MakerTestDetailsTest.php
Labels: Bug

#1445 [make:entity] use ux-turbo instead of ux-turbo-mercure
  docker-compose.yml
  src/Maker/MakeEntity.php
  tests/Maker/MakeEntityTest.php
Labels: Bug, Status: Reviewed

#1452 [make:entity] remove PhpCompatUtil constructor argument
  src/Maker/MakeEntity.php
  src/Resources/config/makers.xml
Labels: Feature

#1422 Generator verifies if class exists before altering class name
  src/Generator.php
  tests/GeneratorTest.php
Labels: Bug

#1411 [make:user] Add phpdocs in class generated by make:user for PHPStan
  src/Security/UserClassBuilder.php
  tests/Security/fixtures/expected/UserEntityWithEmailAsIdentifier.php
  tests/Security/fixtures/expected/UserEntityWithPassword.php
  tests/Security/fixtures/expected/UserEntityWithUser_IdentifierAsIdentifier.php
  tests/Security/fixtures/expected/UserEntityWithoutPassword.php
  tests/Security/fixtures/expected/UserModelWithEmailAsIdentifier.php
  tests/Security/fixtures/expected/UserModelWithPassword.php
  tests/Security/fixtures/expected/UserModelWithoutPassword.php
Labels: Feature, Status: Reviewed

#1283 don't install development files when adding maker-bundle to a project
  .gitattributes
Labels: Bug

#1450 housekeeping - add rector rules - one step closer to static analysis
  src/Command/MakerCommand.php
  src/Docker/DockerDatabaseServices.php
  src/Doctrine/EntityRegenerator.php
  src/Generator.php
  src/GeneratorTwigHelper.php
  src/Maker/MakeAuthenticator.php
  src/Maker/MakeDockerDatabase.php
  src/Maker/MakeEntity.php
  src/Maker/MakeListener.php
  src/Maker/MakeRegistrationForm.php
  src/Maker/MakeResetPassword.php
  src/Maker/MakeStimulusController.php
  src/Maker/MakeSubscriber.php
  src/Maker/MakeTest.php
  src/Maker/MakeUser.php
  src/Maker/Security/MakeFormLogin.php
  src/Security/InteractiveSecurityHelper.php
  src/Security/SecurityConfigUpdater.php
  src/Util/ClassSourceManipulator.php
  src/Util/YamlSourceManipulator.php
Labels: Minor

#1456 [git-released] v1.55.0
  CHANGELOG.md
Labels: Status: Reviewed, Minor

#1458 [make:entity] fix require mercure before asking to broadcast entity updates
  src/Maker/MakeEntity.php
  tests/Maker/MakeEntityTest.php
Labels: Bug

#1459 [release] v1.55.1
  CHANGELOG.md
Labels: Minor

#1461 [make:auth] Fix 'always-remember-me' param always set to true
  src/Maker/MakeAuthenticator.php
  tests/Maker/MakeAuthenticatorTest.php
Labels: Bug, Status: Reviewed

#1393 [make:*] add `single_text` widget for all date types
  src/Doctrine/EntityDetails.php
Labels: Feature, Status: Reviewed

#1405 [make:reset-password] increase password strength & check for comprimised password
  src/Maker/MakeResetPassword.php
  src/Resources/skeleton/resetPassword/ChangePasswordFormType.tpl.php
Labels: Feature, Status: Reviewed

#1460 [make:user] handle ORM\Column.unique deprecation - use ORM\UniqueConstrain
  src/Security/UserClassBuilder.php
  src/Util/ClassSourceManipulator.php
  tests/Security/fixtures/expected/UserEntityWithEmailAsIdentifier.php
  tests/Security/fixtures/expected/UserEntityWithPassword.php
  tests/Security/fixtures/expected/UserEntityWithUser_IdentifierAsIdentifier.php
  tests/Security/fixtures/expected/UserEntityWithoutPassword.php
Labels: Feature, Status: Reviewed

#1465 [make:twig-component] default to "no" when asking if is live component
  src/Maker/MakeTwigComponent.php
  tests/Maker/MakeTwigComponentTest.php
Labels: Feature, Status: Needs Review

#1468 [make:crud] fixed issues with make CRUD test Controller generation
  src/Resources/skeleton/crud/test/Test.EntityManager.tpl.php
Labels: Bug, Status: Reviewed
